### ISSUE TITLE
I used tag 11.0-2.5, but Postgis version appears to be 3.0

### ISSUE THREAD

**Issue by lswainemoore** [kartoza/docker-postgis#172] opened 2019-12-15 20:33 UTC
thanks for setting this up! 

```
> docker exec -it pg11.0-2.5 /bin/bash -c "PGPASSWORD=docker psql postgres -U docker -h localhost"
psql (11.6 (Debian 11.6-1.pgdg100+1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

postgres=# SELECT PostGIS_version();
            postgis_version
---------------------------------------
 3.0 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
(1 row)
```

am I wrong to expect `PostGIS_version()` should show 2.5?

**Comment by NyakudyaA** [comment] 2019-12-15 20:56
It should show 2.5 but will check tomorrow what is happening

**Comment by lswainemoore** [comment] 2019-12-15 22:42
thank you!

**Comment by yosukefk** [comment] 2019-12-21 01:53
I see the same, and also with `select postgis_full_version();`, it doesn't seem like RASTER support is not enabled...

**Comment by NyakudyaA** [comment] 2019-12-21 12:41
> I see the same, and also with `select postgis_full_version();`, it doesn't seem like RASTER support is not enabled...

I have checked but can seem to see why the wrong version is being shown. @yosukefk is there any postgis function in 3 that is running in this version.

I tried to run the following https://www.postgresql.org/docs/12/ddl-generated-columns.html
but it gives me an error.

Postgis raster can be installed with the environment variable MULTIPLE_EXTENSIONS on runtime

**Comment by yosukefk** [comment] 2019-12-21 15:43
Thanks, the MULTIPLE_EXTENSIONS env variable, i will give it a shot today, and come back here.  However,...

I tried to see if i can move to PostgeSQL 12 now.  
At this point I don't want to update to Postgresql12, there seems to be problems caused by deprecated functionality like one this example https://github.com/sqlalchemy/sqlalchemy/issues/4463 , that can be solved, but version dependency of various tools i have makes it hard to incorporate all the necessary fixes into my application.

I am not quite sure what you want meto try by 

>  is there any postgis function in 3 that is running in this version.

**Comment by NyakudyaA** [comment] 2019-12-21 15:48
> Thanks, the MULTIPLE_EXTENSIONS env variable, i will give it a shot today, and come back here.
> 
> At this point I don't want to update to Postgresql12, there seems to be problems caused by deprecated functionality like one this example [sqlalchemy/sqlalchemy#4463](https://github.com/sqlalchemy/sqlalchemy/issues/4463) , that can be solved, but version dependency of various tools i have makes it hard to incorporate all the necessary fixes into my application.

What I meant is that it shows version 3 but it still is actually version 2.5 in that image

**Comment by yosukefk** [comment] 2019-12-21 15:50
> What I meant is that it shows version 3 but it still is actually version 2.5 in that image

Is this what you believe, or is this your hypothesis that you want to test?

**Comment by NyakudyaA** [comment] 2019-12-21 16:03
> > What I meant is that it shows version 3 but it still is actually version 2.5 in that image
> 
> Is this what you believe, or is this your hypothesis that you want to test?

I tried to run the following in the image
```
CREATE TABLE people (
    id serial primary key,
    height_cm numeric,
    height_in numeric GENERATED ALWAYS AS (height_cm / 2.54) STORED
);
```
Which is apparently listed in the changelog for 12 as the new goodies and it gave an error.
But still, the version should still show 2.5

**Comment by yosukefk** [comment] 2019-12-21 18:35
I see your point, 

This is what I get from the layer for kartoza/postgis:11.0-2.5, Image ID366b8ce10e5a, Created 2019-08-01T07:03:06.580147038Z 

<pre>
gis=# select version();
                                                     version
------------------------------------------------------------------------------------------------------------------
 PostgreSQL 11.4 (Debian 11.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
(1 row)

gis=# select postgis_full_version();
                                                                                                        postgis_full_ver
sion
------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------
 POSTGIS="2.5.2 r17328" [EXTENSION] PGSQL="110" GEOS="3.7.1-CAPI-1.11.1 27a5e771" PROJ="Rel. 5.2.0, September 15th, 2018
" GDAL="GDAL 2.4.0, released 2018/12/14" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.3.1" TOPOLOGY RASTER
(1 row)

gis=#
</pre>

I tried ST_AsGeoJSON https://postgis.net/docs/ST_AsGeoJSON.html, it would export SRID if it is not WGS84, starting PostGIS 3.

This is what I get:

<pre>
gis=# select st_asgeojson( st_setsrid(st_point(1,1), 3785));
             st_asgeojson
--------------------------------------
 {"type":"Point","coordinates":[1,1]}
(1 row)

gis=#
</pre>

So it means that PostGIS in the image is likely to be earlier than 3.


And this is what I am getting today if i pull the image for 11.0-2.5, Image ID=9617bb107baf  Created 2019-12-13T12:57:28.05967895Z

<pre>
gis=# select version();

                                                     version                                                      

------------------------------------------------------------------------------------------------------------------

 PostgreSQL 11.6 (Debian 11.6-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

(1 row)


gis=# select postgis_full_version();

                                                                                              postgis_full_version                                                                                              

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 POSTGIS="3.0.0 r17983" [EXTENSION] PGSQL="110" GEOS="3.7.1-CAPI-1.11.1 27a5e771" PROJ="Rel. 5.2.0, September 15th, 2018" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.3.1" WAGYU="0.4.3 (Internal)" TOPOLOGY

(1 row)


gis=# 
</pre>

So apparently Postgresql changed from 11.4 to 11.6, then postgis from 2.5.2 to 3.0.0, even though they are both tagged as kartoza/postgis:11.0-2.5.    With this new image, i am getting follows.
<pre>
gis=# select st_asgeojson(st_setsrid(st_point(1,1), 3785));

                                         st_asgeojson                                         

----------------------------------------------------------------------------------------------

 {"type":"Point","crs":{"type":"name","properties":{"name":"EPSG:3785"}},"coordinates":[1,1]}

(1 row)


gis=# 
</pre>

The output geojson include EPSG id as it is claimed in postgis documentation.  So it is one single test but the image for kartoza/postgis:11.0-2.5 (9617bb107baf) has  postgis 3.

Would be nice that this got straighed out.  But as I know what version i have in the repositoty, i enable RASTER at runtime as you told me how, and see if it would work for my application.

**Comment by NyakudyaA** [comment] 2019-12-21 19:57
Hi @yosukefk i will fix this I think I have a clue on how to do it

**Comment by yosukefk** [comment] 2019-12-22 00:52
@NyakudyaA , It turned out that for my application, the only thing I have to "fix" was to enable raster support.  Everything  else seems to be fine with PostgreSQL11 and PostGIS3.  So in my Dockerfile, I did, near toward the end,

```
FROM kartoza/postgis:11.0-2.5

# other stuff here

ENV POSTGRES_MULTIPLE_EXTENSIONS=postgis,postgis_raster
RUN echo "psql -d gis -c 'create extension postgis_raster;'" >> /docker-entrypoint.sh
ENTRYPOINT /docker-entrypoint.sh
```

I am wondering though, do you know if this causes trouble if raster is enabled compile time?   Or can i just keep this way and error can be safely ignored?

**Comment by NyakudyaA** [comment] 2019-12-23 08:31
@yosukefk I think this could be an upstream issue from PostgreSQL. I am going to close this issue.
I have tried to install PostGIS on different distros ie Debian:stretch, Debian:buster and ubuntu:18.04 which all retain the same values. I do no think that there is anything in our configurations that stipulates the installation of PostGIS 3.

![install](https://user-images.githubusercontent.com/2510900/71345553-5f140800-256e-11ea-832b-2f15d6d6f079.png)

**Closed as completed by NyakudyaA** 2019-12-23 08:31 UTC

**Comment by NyakudyaA** [comment] 2019-12-23 08:35
> @NyakudyaA , It turned out that for my application, the only thing I have to "fix" was to enable raster support. Everything else seems to be fine with PostgreSQL11 and PostGIS3. So in my Dockerfile, I did, near toward the end,
> 
> ```
> FROM kartoza/postgis:11.0-2.5
> 
> # other stuff here
> 
> ENV POSTGRES_MULTIPLE_EXTENSIONS=postgis,postgis_raster
> RUN echo "psql -d gis -c 'create extension postgis_raster;'" >> /docker-entrypoint.sh
> ENTRYPOINT /docker-entrypoint.sh
> ```
> 
> I am wondering though, do you know if this causes trouble if raster is enabled compile time? Or can i just keep this way and error can be safely ignored?

Hi I have pushed upstream a new image. It should be built in a couple of minutes.

It should by default have pg_raster installed. Using the docker-compose  

```
# docker-compose build
version: '2.1'
volumes:
  dbbackups:
  postgis-data:

services:

  db:
    image: kartoza/postgis:12.0
    volumes:
      - postgis-data:/var/lib/postgresql
      - dbbackups:/backups
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the three specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster
    ports:
      - 25432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"
```

You do not need to rebuilt the image to activate extensions. When the container starts it basically installs the extensions if they are missing

**Comment by rolep** [comment] 2020-02-25 15:56
Had same issue. Everything worked ok and I thought having newer version is better, but __*it misguides with image tag version*__.

`postgis-3` is probably installed with one of dependencies as most recent version. Correct version can be installed manually (`CREATE EXTENSION postgis WITH VERSION '2.5'`), however it complicates things and is not expected behavior if version is in the tag.

As I am using [custom image with Nominatim](https://github.com/rolep/nominatim-devops) (need to copy lib to be used by postgresql query) and it suggests using Postgres 11 and PostGIS 2.5, I have added simple remove and check steps to `Dockerfile`:

```
FROM kartoza/postgis:11.0-2.5 AS nominatim-postgres

# Remove PostGIS 3.0 as it is also present and will be used by default, but we need 2.5
# and check 2.5 version is installed
RUN apt-get remove -y postgresql-11-postgis-3 postgresql-11-postgis-3-scripts || true; \
    dpkg-query -W -f='${Status}' postgresql-11-postgis-2.5 | grep -xq 'install ok installed' && \
    dpkg-query -W -f='${Status}' postgresql-11-postgis-2.5-scripts | grep -xq 'install ok installed'
```
