### ISSUE TITLE
PROMOTE_MASTER does not work

### ISSUE THREAD

**Issue by mshzsh** [kartoza/docker-postgis#336] opened 2021-10-09 12:59 UTC
After down the Master server, it is not possible to use the `PROMOTE_MASTER` option on the Slave server

**Comment by NyakudyaA** [comment] 2022-04-26 21:38
Duplicate of https://github.com/kartoza/docker-postgis/issues/325#issue-976084287

**Closed as completed by NyakudyaA** 2022-04-26 21:38 UTC
